### ISSUE TITLE
Not able to connect to thingsboard server running on aws

### ISSUE THREAD

**Issue by Nitheshnithu121** [awslabs/aws-crt-builder#42]
i have created EC2 instance in aws and installed ubuntu and i have installed thingsboard server on it and iam able to run the server and i can open it using its public DNS or public ip ,but the the problem is when i am trying to connect this server(thingsboard) using my arduino code it fails to connect the server ,is there any security issues to connect this server..???? 
Can any one please help me to solve this problem

**Comment by bretambrose** [comment]
Hello,

I think you may have the wrong repository.  The aws-crt-* and aws-c-* libraries do not really support arduino as a use case.  I'm not sure Aws Iot Sdks make sense for connecting to a thingboard server (which appears to just require a low-level mqtt client).  In the case where it does make sense, you may be looking for https://github.com/aws/aws-iot-device-sdk-arduino-yun or https://github.com/aws/aws-iot-device-sdk-embedded-C  

If you do create another issue, you will need to provide more context on the problem you are having: code snippets, libraries used, console output and/or logs at the very least.
